server:
  port: 8083

spring:
  application:
    name: order-service
  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: order_db
    schema-action: create_if_not_exists

item:
  service:
    url: http://localhost:8082