server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 2000824c

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true